CREATE TABLE `users` (
    `user_id` SERIAL NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `user_name` VARCHAR(25) NOT NULL UNIQUE,
    `password` VARCHAR(255) NOT NULL,
    `email` VARCHAR(255) NOT NULL,
    `last_login_time` TIMESTAMP,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)